use_frameworks!

target 'CleanyModal_Example' do
  pod 'CleanyModal', :path => '../'

#  target 'CleanyModal_Tests' do
#    inherit! :search_paths

#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0.2'
#  end
end
